<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="41" started-at="2018-10-05T14:05:44Z" finished-at="2018-10-05T14:05:44Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="41" started-at="2018-10-05T14:05:44Z" finished-at="2018-10-05T14:05:44Z">
      <class name="com.manthan.steps.LoginSteps">
        <test-method status="FAIL" signature="loginIntoApp()[pri:0, instance:com.manthan.steps.LoginSteps@5622fdf]" name="loginIntoApp" duration-ms="9" started-at="2018-10-05T14:05:44Z" description="Login into application" finished-at="2018-10-05T14:05:44Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method LoginSteps.loginIntoApp()[pri:0, instance:com.manthan.steps.LoginSteps@5622fdf] should have thrown an exception of type class java.lang.Exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method LoginSteps.loginIntoApp()[pri:0, instance:com.manthan.steps.LoginSteps@5622fdf] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:80)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1139)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:612)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginIntoApp -->
      </class> <!-- com.manthan.steps.LoginSteps -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
